### ISSUE TITLE
VOT2019 longterm:LP_struct_trax_properties instance instead of dict

### ISSUE THREAD

**Issue by Daikenan** [votchallenge/vot-toolkit#217]
When I test toolkit in VOT2019 longterm challenge, I always find error like this:
frame: 1  Region: 706.39,360.68,52.75,115.05
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/daikenan/Tracking/MBMD_vot_code/MBMD_vot_code/MBMD_Reimplement_v7.py", line 1608, in <module>
    handle.report(region, confidence)
  File "/home/daikenan/Tracking/MBMD_vot_code/MBMD_vot_code/vot.py", line 86, in report
    self._trax.status(tregion, properties)
  File "/home/daikenan/Tracking/benchmark/VOT2019/vot2019lt/native/trax/support/python/trax/server.py", line 102, in status
    tproperties = Properties(properties)
  File "/home/daikenan/Tracking/benchmark/VOT2019/vot2019lt/native/trax/support/python/trax/__init__.py", line 46, in __init__
    trax_properties_set(self._ref.reference(), key, str(value))
ctypes.ArgumentError: argument 1: <type 'exceptions.TypeError'>: expected LP_struct_trax_properties instance instead of dict
Traceback (most recent call last):
@@TRAX:quit 
  File "/home/daikenan/Tracking/benchmark/VOT2019/vot2019lt/native/trax/support/python/trax/wrapper.py", line 17, in _run_finalizer

I found that the format of  'confidence score' was different from VOT2018 longterm challenge.In VOT2018, the format of 'confidence score' was a dict, but in VOT2019, it was 'LP_struct_trax_properties instance',I don't know how to convert to this format.
When I do not send 'confident score' into handle.report, just sent a 'region', like this: 
handle.report(region)
it works, this also validates my thoughts.
So, what is the correct format of 'confidence score' and how to convert it?

**Comment by lawpdas** [comment]
The `python_ncc` has the same problem.  
And `imagefile` returned by `handle.frame()` is not a string of image's path, instead, a tuple. https://github.com/votchallenge/vot-toolkit/blob/c03b406734c0bcd33f7a3c2fb9519b8b07dbb83f/tracker/examples/python/vot.py#L97
...Can I use old version toolkit for votlt19 ?

**Comment by lukacu** [comment]
Thanks for reporting this, it is a bug and we will fix it in the following days.

**Comment by lukacu** [comment]
I have fixed the first error, it is currently available in trax master. I am not sure about the problem in the fist comment, it seems unrelated. @lawpdas can you provide a bit more information? The tuple code should only be used when more channels are used, e.g. in RGBD and RGB-TIR challenges.

**Comment by lawpdas** [comment]
@lukacu Thanks!
I tested my RGB long-term tracker and ncc tracker in votlt19 challenge. Because the `imagefile` 
 returned by `handle.frame()` is a tuple, instead of a string of image path, this error will be reported:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lt/vot19/Test_VOT.py", line 38, in <module>
    image = cv2.imread(imagefile)
TypeError: bad argument type for built-in operation
```
And the tuple be printed is:
`('F', 'i', 'l', 'e', ' ', 'r', 'e', 's', 'o', 'u', 'r', 'c', 'e', ' ', 'a', 't', ' ', "'", 'b', "'", '/', 'h', 'o', 'm', 'e', '/', 'l', 't', '/', 'v', 'o', 't', '1', '9', '/', 'v', 'o', 't', '-', 't', 'o', 'o', 'l', 'k', 'i', 't', '-', 'm', 'a', 's', 't', 'e', 'r', '/', 'V', 'O', 'T', '1', '9', '/', 's', 'e', 'q', 'u', 'e', 'n', 'c', 'e', 's', '/', 'b', 'i', 'c', 'y', 'c', 'l', 'e', '/', 'c', 'o', 'l', 'o', 'r', '/', '0', '0', '0', '0', '0', '0', '0', '1', '.', 'j', 'p', 'g', "'", "'")`

So I have to change `handle.frame()` to `return str(image)[20:-2]` to get the correct path string.

**Comment by lukacu** [comment]
Hm, that is clearly wrong, it was a simple bug and should be fixed now.

**Comment by jimiolaniyan** [comment]
@lawpdas how were you able to print the output of the tuple. A simple `print` doesn’t show in the console.

**Comment by lawpdas** [comment]
@lukacu Thanks! 
In my case, `image` will be returned at line97. So I remove line94-line97.
And the image path is still not correct, such as:
```File resource at 'b'/home/lt/vot19/vot-toolkit-7.0.1/VOT19/sequences/ballet/color/00000002.jpg''```
It should be `return image[0][20:-2]`
@jimiolaniyan You can save it to a txt file.

**Comment by Alexadlu** [comment]
> @lukacu Thanks!
> I tested my RGB long-term tracker and ncc tracker in votlt19 challenge. Because the `imagefile`
> returned by `handle.frame()` is a tuple, instead of a string of image path, this error will be reported:
> 
> ```python
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/lt/vot19/Test_VOT.py", line 38, in <module>
>     image = cv2.imread(imagefile)
> TypeError: bad argument type for built-in operation
> ```
> 
> And the tuple be printed is:
> `('F', 'i', 'l', 'e', ' ', 'r', 'e', 's', 'o', 'u', 'r', 'c', 'e', ' ', 'a', 't', ' ', "'", 'b', "'", '/', 'h', 'o', 'm', 'e', '/', 'l', 't', '/', 'v', 'o', 't', '1', '9', '/', 'v', 'o', 't', '-', 't', 'o', 'o', 'l', 'k', 'i', 't', '-', 'm', 'a', 's', 't', 'e', 'r', '/', 'V', 'O', 'T', '1', '9', '/', 's', 'e', 'q', 'u', 'e', 'n', 'c', 'e', 's', '/', 'b', 'i', 'c', 'y', 'c', 'l', 'e', '/', 'c', 'o', 'l', 'o', 'r', '/', '0', '0', '0', '0', '0', '0', '0', '1', '.', 'j', 'p', 'g', "'", "'")`
> 
> So I have to change `handle.frame()` to `return str(image)[20:-2]` to get the correct path string.

Can you tell me how you output the result of the variable?thank you

**Comment by lawpdas** [comment]
@lukacu
https://github.com/votchallenge/vot-toolkit/blob/2e5153350499cd7188337c98ee8a0e75dac54e70/tracker/examples/python/vot.py#L97
This line should be change to `return str(image)[20:-2]` for RGB-LT tracker. This solves my problem.
@Alexadlu You can save it to a txt file.

**Comment by Alexadlu** [comment]
Thank you very much, I have referred to your solution for this problem, I have already solved it.However, I have encountered a new problem and I don't know if you have ever encountered it. That is, when I execute the run_ experiment file, I can execute the first five sequences, but the sixth sequence will have an error. I found out through debugging that the tracking failed frame occurred in the sixth sequence. of. I found that running the vot toolkit will directly discard the next five frames when you encounter a frame that fails to track, and perform the restart execution initialization through the subsequent sixth frame, thus causing the missing tagert_bbox data to be interrupted. I don't know if you have some solutions. The debug console output is as follows. The toolbox for vot2019 is used.

I would be very grateful if you can take the time to reply to me. Thanks again
------------------ 原始邮件 ------------------
发件人: "Lawpdas"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 下午5:32
收件人: "votchallenge/vot-toolkit"<vot-toolkit@noreply.github.com>;
抄送: "今日"<1214670665@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [votchallenge/vot-toolkit] VOT2019longterm:LP_struct_trax_properties instance instead of dict (#217)




@lukacu
 https://github.com/votchallenge/vot-toolkit/blob/2e5153350499cd7188337c98ee8a0e75dac54e70/tracker/examples/python/vot.py#L97
 This line should be change to return str(image)[20:-2] for RGB-LT tracker. This solves my problem.
 @Alexadlu You can save it to a txt file.

**Comment by lukacu** [comment]
This should be fixed now, please update the toolkit.
